echo STOP AND DELETE MINIKUBE..................................................................

minikube stop
minikube delete

echo FINISHED STOPPING AND DELETING MINIKUBE...................................................
echo ..........................................................................................
echo START MINIKUBE............................................................................

minikube start

echo FINISHED STARTING MINIKUBE................................................................
echo ..........................................................................................
echo SETTING ENVIRONMENT VARIABLES OF MINIKUBE.................................................

eval $(minikube docker-env)

echo FINISHED SETTING ENVIRONMENT VARIABLES OF MINIKUBE........................................
echo ..........................................................................................
echo START BUILDING DOCKER IMAGE...............................................................

cd ../../..
./mvnw clean package -Dquarkus.container-image.build=true

echo FINISHED BUILDING DOCKER IMAGE............................................................
echo ..........................................................................................
echo START PUSHING SERVICE TO MINIKUBE CLUSTER.................................................

kubectl apply -f target/kubernetes/minikube.json

echo FINISHED PUSHING SERVICE TO MINIKUBE CLUSTER.................................................
echo .............................................................................................
echo START SERVICE IN MINIKUBE CLUSTER............................................................

minikube service list
minikube service chat-microservice
